export interface College {
  id: string;
  name: string;
  shortName: string;
  location: string;
  state: string;
  region: "North" | "South" | "East" | "West" | "Central";
  type: "IIT" | "NIT" | "IIIT" | "BITS" | "State Government" | "Private" | "Deemed" | "Central University";
  exam: string[];
  minRank: number;
  maxRank: number;
  annualFee: number;
  totalFee: number;
  courseDuration: number;
  nirfRanking: number;
  placementAvg: number;
  placementHighest: number;
  placementRate: number;
  branches: string[];
  hostel: boolean;
  scholarships: boolean;
  accreditation: string;
  website: string;
  highlights: string[];
}

export const colleges: College[] = [
  {
    id: "iit-bombay",
    name: "Indian Institute of Technology Bombay",
    shortName: "IIT Bombay",
    location: "Mumbai",
    state: "Maharashtra",
    region: "West",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 1200,
    annualFee: 230000,
    totalFee: 920000,
    courseDuration: 4,
    nirfRanking: 3,
    placementAvg: 2100000,
    placementHighest: 27000000,
    placementRate: 95,
    branches: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering", "Aerospace Engineering", "Civil Engineering", "Metallurgical Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.iitb.ac.in",
    highlights: ["Top 3 IIT", "Strong research culture", "Excellent placements", "Powai campus"],
  },
  {
    id: "iit-delhi",
    name: "Indian Institute of Technology Delhi",
    shortName: "IIT Delhi",
    location: "New Delhi",
    state: "Delhi",
    region: "North",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 1500,
    annualFee: 225000,
    totalFee: 900000,
    courseDuration: 4,
    nirfRanking: 2,
    placementAvg: 2050000,
    placementHighest: 26000000,
    placementRate: 94,
    branches: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering", "Civil Engineering", "Textile Engineering", "Biotech"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.iitd.ac.in",
    highlights: ["Capital location", "NIRF Rank 2", "Strong alumni network", "Diverse branches"],
  },
  {
    id: "iit-madras",
    name: "Indian Institute of Technology Madras",
    shortName: "IIT Madras",
    location: "Chennai",
    state: "Tamil Nadu",
    region: "South",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 1300,
    annualFee: 220000,
    totalFee: 880000,
    courseDuration: 4,
    nirfRanking: 1,
    placementAvg: 2150000,
    placementHighest: 28000000,
    placementRate: 96,
    branches: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering", "Aerospace Engineering", "Naval Architecture"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.iitm.ac.in",
    highlights: ["NIRF Rank 1", "Best placements", "Research park", "Green campus"],
  },
  {
    id: "iit-kanpur",
    name: "Indian Institute of Technology Kanpur",
    shortName: "IIT Kanpur",
    location: "Kanpur",
    state: "Uttar Pradesh",
    region: "North",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 2500,
    annualFee: 218000,
    totalFee: 872000,
    courseDuration: 4,
    nirfRanking: 4,
    placementAvg: 1850000,
    placementHighest: 22000000,
    placementRate: 90,
    branches: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Aerospace Engineering", "Chemical Engineering", "Civil Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.iitk.ac.in",
    highlights: ["Pioneer in CS education", "Strong entrepreneurship", "Research excellence"],
  },
  {
    id: "iit-kharagpur",
    name: "Indian Institute of Technology Kharagpur",
    shortName: "IIT Kharagpur",
    location: "Kharagpur",
    state: "West Bengal",
    region: "East",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 3500,
    annualFee: 210000,
    totalFee: 1050000,
    courseDuration: 5,
    nirfRanking: 5,
    placementAvg: 1650000,
    placementHighest: 20000000,
    placementRate: 88,
    branches: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Architecture", "Mining Engineering", "Ocean Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.iitkgp.ac.in",
    highlights: ["Oldest IIT", "Largest campus", "Diverse programs", "5-year integrated courses"],
  },
  {
    id: "iit-roorkee",
    name: "Indian Institute of Technology Roorkee",
    shortName: "IIT Roorkee",
    location: "Roorkee",
    state: "Uttarakhand",
    region: "North",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 4500,
    annualFee: 215000,
    totalFee: 860000,
    courseDuration: 4,
    nirfRanking: 6,
    placementAvg: 1550000,
    placementHighest: 18000000,
    placementRate: 86,
    branches: ["Computer Science", "Electrical Engineering", "Civil Engineering", "Chemical Engineering", "Mechanical Engineering", "Architecture"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.iitr.ac.in",
    highlights: ["Historic institution (1847)", "Strong civil engineering", "Beautiful hill campus"],
  },
  {
    id: "iit-guwahati",
    name: "Indian Institute of Technology Guwahati",
    shortName: "IIT Guwahati",
    location: "Guwahati",
    state: "Assam",
    region: "East",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 5000,
    annualFee: 212000,
    totalFee: 848000,
    courseDuration: 4,
    nirfRanking: 7,
    placementAvg: 1400000,
    placementHighest: 16000000,
    placementRate: 84,
    branches: ["Computer Science", "Electronics", "Mechanical Engineering", "Chemical Engineering", "Civil Engineering", "Design"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.iitg.ac.in",
    highlights: ["Scenic Brahmaputra campus", "Rising research output", "Strong design program"],
  },
  {
    id: "iit-hyderabad",
    name: "Indian Institute of Technology Hyderabad",
    shortName: "IIT Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    region: "South",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 6000,
    annualFee: 218000,
    totalFee: 872000,
    courseDuration: 4,
    nirfRanking: 8,
    placementAvg: 1350000,
    placementHighest: 15000000,
    placementRate: 83,
    branches: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering", "Civil Engineering", "AI & ML"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.iith.ac.in",
    highlights: ["Near IT hub", "AI/ML specialization", "Industry collaborations"],
  },
  {
    id: "iit-bhu",
    name: "Indian Institute of Technology (BHU) Varanasi",
    shortName: "IIT BHU",
    location: "Varanasi",
    state: "Uttar Pradesh",
    region: "North",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 5500,
    annualFee: 215000,
    totalFee: 1075000,
    courseDuration: 5,
    nirfRanking: 11,
    placementAvg: 1450000,
    placementHighest: 16000000,
    placementRate: 85,
    branches: ["Computer Science", "Electronics", "Mechanical Engineering", "Electrical Engineering", "Civil Engineering", "Metallurgical Engineering", "Mining Engineering", "Ceramic Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.iitbhu.ac.in",
    highlights: ["Part of BHU", "Cultural heritage", "Unique branches", "Growing rapidly"],
  },
  {
    id: "iit-indore",
    name: "Indian Institute of Technology Indore",
    shortName: "IIT Indore",
    location: "Indore",
    state: "Madhya Pradesh",
    region: "Central",
    type: "IIT",
    exam: ["JEE Advanced"],
    minRank: 1,
    maxRank: 7000,
    annualFee: 218000,
    totalFee: 872000,
    courseDuration: 4,
    nirfRanking: 13,
    placementAvg: 1300000,
    placementHighest: 14000000,
    placementRate: 82,
    branches: ["Computer Science", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Metallurgical Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.iiti.ac.in",
    highlights: ["Fast-rising IIT", "Modern campus", "Strong research"],
  },
  {
    id: "nit-trichy",
    name: "National Institute of Technology Tiruchirappalli",
    shortName: "NIT Trichy",
    location: "Tiruchirappalli",
    state: "Tamil Nadu",
    region: "South",
    type: "NIT",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 8000,
    annualFee: 155000,
    totalFee: 620000,
    courseDuration: 4,
    nirfRanking: 9,
    placementAvg: 1200000,
    placementHighest: 14000000,
    placementRate: 90,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering", "Instrumentation"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.nitt.edu",
    highlights: ["Best NIT", "Pragyan tech fest", "Strong placements for NIT"],
  },
  {
    id: "nit-warangal",
    name: "National Institute of Technology Warangal",
    shortName: "NIT Warangal",
    location: "Warangal",
    state: "Telangana",
    region: "South",
    type: "NIT",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 12000,
    annualFee: 148000,
    totalFee: 592000,
    courseDuration: 4,
    nirfRanking: 12,
    placementAvg: 1050000,
    placementHighest: 12000000,
    placementRate: 85,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering", "Biotechnology"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.nitw.ac.in",
    highlights: ["Top 3 NIT", "Strong alumni network", "Technozion fest"],
  },
  {
    id: "nit-surathkal",
    name: "National Institute of Technology Karnataka (Surathkal)",
    shortName: "NIT Surathkal",
    location: "Mangalore",
    state: "Karnataka",
    region: "South",
    type: "NIT",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 10000,
    annualFee: 168000,
    totalFee: 672000,
    courseDuration: 4,
    nirfRanking: 10,
    placementAvg: 1150000,
    placementHighest: 13000000,
    placementRate: 88,
    branches: ["Computer Science", "Electronics", "Mechanical Engineering", "Chemical Engineering", "Civil Engineering", "Information Technology"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.nitk.ac.in",
    highlights: ["Beach campus", "Top 3 NIT", "Engineer tech fest"],
  },
  {
    id: "nit-rourkela",
    name: "National Institute of Technology Rourkela",
    shortName: "NIT Rourkela",
    location: "Rourkela",
    state: "Odisha",
    region: "East",
    type: "NIT",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 15000,
    annualFee: 140000,
    totalFee: 560000,
    courseDuration: 4,
    nirfRanking: 15,
    placementAvg: 950000,
    placementHighest: 10000000,
    placementRate: 82,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Metallurgical Engineering", "Mining Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.nitrkl.ac.in",
    highlights: ["Strong metallurgy program", "Research focus", "Affordable fees"],
  },
  {
    id: "nit-calicut",
    name: "National Institute of Technology Calicut",
    shortName: "NIT Calicut",
    location: "Kozhikode",
    state: "Kerala",
    region: "South",
    type: "NIT",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 14000,
    annualFee: 145000,
    totalFee: 580000,
    courseDuration: 4,
    nirfRanking: 16,
    placementAvg: 1000000,
    placementHighest: 12000000,
    placementRate: 84,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Architecture"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.nitc.ac.in",
    highlights: ["Top 5 NIT", "Kerala quality of life", "Strong academics"],
  },
  {
    id: "nit-allahabad",
    name: "Motilal Nehru National Institute of Technology Allahabad",
    shortName: "MNNIT Allahabad",
    location: "Prayagraj",
    state: "Uttar Pradesh",
    region: "North",
    type: "NIT",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 18000,
    annualFee: 142000,
    totalFee: 568000,
    courseDuration: 4,
    nirfRanking: 25,
    placementAvg: 900000,
    placementHighest: 11000000,
    placementRate: 80,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.mnnit.ac.in",
    highlights: ["Historic NIT", "Good CS placements", "Affordable"],
  },
  {
    id: "bits-pilani",
    name: "Birla Institute of Technology and Science, Pilani",
    shortName: "BITS Pilani",
    location: "Pilani",
    state: "Rajasthan",
    region: "North",
    type: "BITS",
    exam: ["BITSAT"],
    minRank: 1,
    maxRank: 3000,
    annualFee: 520000,
    totalFee: 2080000,
    courseDuration: 4,
    nirfRanking: 22,
    placementAvg: 1650000,
    placementHighest: 20000000,
    placementRate: 92,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering", "Civil Engineering", "Pharmacy"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A",
    website: "https://www.bits-pilani.ac.in",
    highlights: ["Practice school program", "Flexible curriculum", "Strong industry ties", "Premium private"],
  },
  {
    id: "bits-goa",
    name: "BITS Pilani - Goa Campus",
    shortName: "BITS Goa",
    location: "Goa",
    state: "Goa",
    region: "West",
    type: "BITS",
    exam: ["BITSAT"],
    minRank: 1,
    maxRank: 5000,
    annualFee: 520000,
    totalFee: 2080000,
    courseDuration: 4,
    nirfRanking: 28,
    placementAvg: 1400000,
    placementHighest: 17000000,
    placementRate: 88,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Chemical Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A",
    website: "https://www.bits-pilani.ac.in/goa",
    highlights: ["Coastal Goa campus", "Practice school", "Growing research"],
  },
  {
    id: "iiit-hyderabad",
    name: "International Institute of Information Technology Hyderabad",
    shortName: "IIIT Hyderabad",
    location: "Hyderabad",
    state: "Telangana",
    region: "South",
    type: "IIIT",
    exam: ["JEE Main", "UGEE"],
    minRank: 1,
    maxRank: 5000,
    annualFee: 310000,
    totalFee: 1240000,
    courseDuration: 4,
    nirfRanking: 30,
    placementAvg: 1800000,
    placementHighest: 24000000,
    placementRate: 95,
    branches: ["Computer Science", "Electronics", "Computer Science & Design"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.iiit.ac.in",
    highlights: ["Best for CS", "Research-driven", "Strong startup culture", "Near IT hub"],
  },
  {
    id: "iiit-bangalore",
    name: "International Institute of Information Technology Bangalore",
    shortName: "IIIT Bangalore",
    location: "Bangalore",
    state: "Karnataka",
    region: "South",
    type: "IIIT",
    exam: ["JEE Main", "COMEDK"],
    minRank: 1,
    maxRank: 8000,
    annualFee: 350000,
    totalFee: 1400000,
    courseDuration: 4,
    nirfRanking: 45,
    placementAvg: 1500000,
    placementHighest: 18000000,
    placementRate: 92,
    branches: ["Computer Science", "Electronics", "Information Technology"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A",
    website: "https://www.iiitb.ac.in",
    highlights: ["Silicon Valley of India", "IT industry proximity", "Strong placements"],
  },
  {
    id: "iiit-allahabad",
    name: "Indian Institute of Information Technology Allahabad",
    shortName: "IIIT Allahabad",
    location: "Prayagraj",
    state: "Uttar Pradesh",
    region: "North",
    type: "IIIT",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 12000,
    annualFee: 185000,
    totalFee: 740000,
    courseDuration: 4,
    nirfRanking: 52,
    placementAvg: 1200000,
    placementHighest: 14000000,
    placementRate: 88,
    branches: ["Information Technology", "Computer Science", "Electronics"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A",
    website: "https://www.iiita.ac.in",
    highlights: ["Strong CS program", "Government funded", "Good placements for IIIT"],
  },
  {
    id: "dtu",
    name: "Delhi Technological University",
    shortName: "DTU",
    location: "New Delhi",
    state: "Delhi",
    region: "North",
    type: "State Government",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 18000,
    annualFee: 175000,
    totalFee: 700000,
    courseDuration: 4,
    nirfRanking: 35,
    placementAvg: 1200000,
    placementHighest: 15000000,
    placementRate: 85,
    branches: ["Computer Science", "Information Technology", "Electronics", "Mechanical Engineering", "Civil Engineering", "Software Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.dtu.ac.in",
    highlights: ["Delhi location", "Strong placements", "Affordable", "Ex-DCE legacy"],
  },
  {
    id: "nsut",
    name: "Netaji Subhas University of Technology",
    shortName: "NSUT",
    location: "New Delhi",
    state: "Delhi",
    region: "North",
    type: "State Government",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 20000,
    annualFee: 170000,
    totalFee: 680000,
    courseDuration: 4,
    nirfRanking: 40,
    placementAvg: 1100000,
    placementHighest: 13000000,
    placementRate: 83,
    branches: ["Computer Science", "Information Technology", "Electronics", "Mechanical Engineering", "Instrumentation"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A",
    website: "https://www.nsut.ac.in",
    highlights: ["Delhi location", "Ex-NSIT", "Growing placements", "Affordable"],
  },
  {
    id: "jadavpur",
    name: "Jadavpur University",
    shortName: "Jadavpur University",
    location: "Kolkata",
    state: "West Bengal",
    region: "East",
    type: "State Government",
    exam: ["WBJEE", "JEE Main"],
    minRank: 1,
    maxRank: 15000,
    annualFee: 18000,
    totalFee: 72000,
    courseDuration: 4,
    nirfRanking: 17,
    placementAvg: 850000,
    placementHighest: 10000000,
    placementRate: 78,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A",
    website: "https://www.jaduniv.edu.in",
    highlights: ["Extremely affordable", "Historic university", "Strong in research", "NIRF top 20"],
  },
  {
    id: "coep",
    name: "College of Engineering Pune",
    shortName: "COEP Pune",
    location: "Pune",
    state: "Maharashtra",
    region: "West",
    type: "State Government",
    exam: ["JEE Main", "MHT-CET"],
    minRank: 1,
    maxRank: 25000,
    annualFee: 130000,
    totalFee: 520000,
    courseDuration: 4,
    nirfRanking: 44,
    placementAvg: 850000,
    placementHighest: 12000000,
    placementRate: 82,
    branches: ["Computer Science", "Electronics", "Mechanical Engineering", "Civil Engineering", "Instrumentation", "Information Technology"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.coep.org.in",
    highlights: ["One of Asia's oldest engineering colleges", "Pune IT hub proximity", "Affordable"],
  },
  {
    id: "vit-vellore",
    name: "Vellore Institute of Technology",
    shortName: "VIT Vellore",
    location: "Vellore",
    state: "Tamil Nadu",
    region: "South",
    type: "Private",
    exam: ["VITEEE"],
    minRank: 1,
    maxRank: 50000,
    annualFee: 250000,
    totalFee: 1000000,
    courseDuration: 4,
    nirfRanking: 11,
    placementAvg: 850000,
    placementHighest: 12000000,
    placementRate: 80,
    branches: ["Computer Science", "Electronics", "Mechanical Engineering", "Civil Engineering", "Biotech", "AI & ML", "Data Science"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.vit.ac.in",
    highlights: ["NIRF rank 11", "Many specializations", "Good infrastructure", "Global exposure"],
  },
  {
    id: "manipal-mit",
    name: "Manipal Institute of Technology",
    shortName: "MIT Manipal",
    location: "Manipal",
    state: "Karnataka",
    region: "South",
    type: "Private",
    exam: ["MET"],
    minRank: 1,
    maxRank: 30000,
    annualFee: 400000,
    totalFee: 1600000,
    courseDuration: 4,
    nirfRanking: 55,
    placementAvg: 750000,
    placementHighest: 10000000,
    placementRate: 78,
    branches: ["Computer Science", "Electronics", "Mechanical Engineering", "Civil Engineering", "Information Technology", "AI & Data Science"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.manipal.edu",
    highlights: ["University town", "Good campus life", "Industry exposure"],
  },
  {
    id: "srm-chennai",
    name: "SRM Institute of Science and Technology",
    shortName: "SRM Chennai",
    location: "Chennai",
    state: "Tamil Nadu",
    region: "South",
    type: "Private",
    exam: ["SRMJEEE"],
    minRank: 1,
    maxRank: 60000,
    annualFee: 300000,
    totalFee: 1200000,
    courseDuration: 4,
    nirfRanking: 32,
    placementAvg: 650000,
    placementHighest: 8000000,
    placementRate: 75,
    branches: ["Computer Science", "Electronics", "Mechanical Engineering", "Civil Engineering", "Biotech", "Data Science"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A++",
    website: "https://www.srmist.edu.in",
    highlights: ["Large campus", "Multiple specializations", "Research focus"],
  },
  {
    id: "thapar",
    name: "Thapar Institute of Engineering and Technology",
    shortName: "Thapar University",
    location: "Patiala",
    state: "Punjab",
    region: "North",
    type: "Deemed",
    exam: ["JEE Main"],
    minRank: 1,
    maxRank: 35000,
    annualFee: 270000,
    totalFee: 1080000,
    courseDuration: 4,
    nirfRanking: 33,
    placementAvg: 850000,
    placementHighest: 10000000,
    placementRate: 82,
    branches: ["Computer Science", "Electronics", "Electrical Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering"],
    hostel: true,
    scholarships: true,
    accreditation: "NAAC A+",
    website: "https://www.thapar.edu",
    highlights: ["Top deemed university", "Good campus", "Industry connections"],
  },
];

export type ExamType =
  | "JEE Advanced"
  | "JEE Main"
  | "BITSAT"
  | "VITEEE"
  | "MET"
  | "SRMJEEE"
  | "WBJEE"
  | "MHT-CET"
  | "COMEDK"
  | "UGEE"
  | "GATE"
  | "Other";

export const examOptions: { value: ExamType; label: string }[] = [
  { value: "JEE Advanced", label: "JEE Advanced" },
  { value: "JEE Main", label: "JEE Main" },
  { value: "BITSAT", label: "BITSAT" },
  { value: "VITEEE", label: "VITEEE" },
  { value: "MET", label: "MET (Manipal)" },
  { value: "SRMJEEE", label: "SRMJEEE" },
  { value: "WBJEE", label: "WBJEE" },
  { value: "MHT-CET", label: "MHT-CET" },
  { value: "COMEDK", label: "COMEDK" },
  { value: "Other", label: "Other" },
];

export const regionOptions = [
  { value: "Any", label: "Any Region" },
  { value: "North", label: "North India" },
  { value: "South", label: "South India" },
  { value: "East", label: "East India" },
  { value: "West", label: "West India" },
  { value: "Central", label: "Central India" },
];

export const stateOptions = [
  "Any",
  "Andhra Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Tamil Nadu",
  "Telangana",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
